#!/bin/bash
CHECKOUT_DIR="/home/lutz/lu-re.files"
GIT_DIR="/home/lutz/lu-re.git"
WWW_DIR="/var/www/lu-re.de"
BRANCH="main"

while read oldrev newrev ref
do
 # only checking out the master (or whatever branch you would like to deploy)
 if [ "$ref" = "refs/heads/$BRANCH" ];
 then
  echo "Ref $ref received. Deploying ${BRANCH} branch to production ..."
  git --work-tree=$CHECKOUT_DIR --git-dir=$GIT_DIR checkout -f $BRANCH
  echo "Installing dependencies & Building site ..."
  cd $CHECKOUT_DIR
  npm install && npm run build
  echo "Clear production directory ..."
  rm -rf $WWW_DIR/.
  echo "Copy files to production directory ..."
  cp -r dist/. $WWW_DIR
 else

  # perform more tasks like migrate and run test, the output of these commands >
echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deploy>"
 fi
done
