#!/bin/bash
TARGET="/home/lutz/www/lu-re.de"
GIT_DIR="/home/lutz/lu-re.git"
BRANCH="main"

while read oldrev newrev ref
do
 # only checking out the master (or whatever branch you would like to deploy)
 if [ "$ref" = "refs/heads/$BRANCH" ];
 then
  echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
  git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
  echo "Installing dependencies & Building site..."
  cd $TARGET
  npm install && npm build
 else

  # perform more tasks like migrate and run test, the output of these commands >
echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deploy>"
 fi
done
